import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [score, setScore] = useState(5)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className = {styles.about}>
        <div className = {styles.aboutLeft}>
          <div className = {styles.aboutUsContainer}>
            <h1 className = {styles.aboutTitle}> About Us</h1>
            <div className= {styles.aboutParagraphContainer}>
              <p className =  {styles.aboutParagraph}>
                My Little Unicorn is a unicorn adoption agency. Our platform allows you to bring a touch of whimsy and wonder into your life by adopting your very own unicorn. These mystical creatures come in all shapes and sizes and each one is as unique as a fingerprint.  
              </p>
            </div>
          </div>
        </div>
        
        <div className = {styles.aboutRight}>
          <div className = {styles.followUsContainer}>
            <h1 className = {styles.followUsTitle}> Follow Us</h1>
            <div>
            <div className={styles.gridContainer}>
            <div className={styles.gridItem}><a href="https://www.instagram.com"><img src="./images/Vectorinsta.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.facebook.com"><img src="./images/Vectorfacebook.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.snapchat.com"><img src="./images/Vectorsnap.png"></img></a></div>  
            <div className={styles.gridItem}><a href="https://www.linkedin.com"><img src="./images/Vectorlinked.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.reddit.com"><img src="./images/Vectorreddit.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.twiiter.com"><img src="./images/Vectortwitter.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.github.com"><img src="./images/Vectorgit.png"></img></a></div>
            <div className={styles.gridItem}><a href="https://www.discord.com"><img src="./images/Vectordiscord.png"></img></a></div>
            </div>
            </div>
            <div className= {styles.followUsSubtitleContainer}>
              <h1 className =  {styles.followUsSubtitle}>
                Give Us FeedBack
              </h1>
              <div className =  {styles.scoreContainer}>
                <div className= {styles.scoreLeft}>
                    <button className = {styles.scoreAdder}
                    onClick = {() => {
                      setScore(score + 1)
                    }}
                    > +1 </button>
                </div>
                <div className= {styles.scoreRight}>
                  <div className = {styles.scoreTextContainer}>
                    <p className = {styles.score}> Score: {score}</p>
                  </div>
                </div>
              </div>
              
            </div>
          </div>

        </div>
      </div>
    </>
  )
}
