import React, { useState, useEffect } from "react"
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Searchbar from 'src/components/Searchbar.js'
import data1 from 'src/info.json';
import { parse } from "node:path/win32"

import horseData from '../info.json'

const inter = Inter({ subsets: ['latin'] })

class Home extends React.Component {
  constructor(props){
    super(props)
    this.state = {
      allHorses: [ 
        {
        "name" : "Jenny",
        "photo" : "./images/unicorn1.jpg"
        },
        {
        "name" : "Jason",
        "photo" : "./images/unicorn2.jpg"
        },
        {
        "name" : "TEST1",
        "photo" : "./images/unicorn2.jpg"
        },
        {
        "name" : "TEST2",
        "photo" : "./images/unicorn1.jpg"
        },
        {
        "name" : "TEST3",
        "photo" : "./images/unicorn2.jpg"
        },
        {
        "name" : "TEST4",
        "photo" : "./images/unicorn2.jpg"
        }
    ],
      changeNewValue: this.changeNewValue.bind(this),
      filter: "",
      filteredHorses: [],
      filterHorses: this.filterHorses.bind(this),
      test: ""
    }


  }

  componentDidMount= () => {
    // var unicorns = horseData
    // var holder = [];
    // for (let i = 0; i < unicorns.length; i++) {
    //   holder.push(unicorns[i]);
    // }
    // this.setState({allHorses: holder, filterHorses: holder, test: "hi"});
    
    // console.log(this.state)
  }
  
  changeNewValue = (input) => {
    this.setState((state,props) => { return {filter: input} } )
    console.log(input)
    this.filterHorses()
  }

  filterHorses = () => {
    var { allHorses, filter } = this.state
    var holder = [];
    if (filter == "") {
      for (let i = 0; i < allHorses.length; i++) {
        holder.push(allHorses[i]);
      }
    } else {
      for (let i = 0; i < allHorses.length; i++) {
        if (allHorses[i].name.toLowerCase().includes(filter.toLowerCase()))
        holder.push(allHorses[i]);
      }
    }
  
    console.log(holder)
    console.log(this.state)

    
  }


  
  render() {
    var {allHorses, filter, filteredHorses, changeNewValue} = this.state
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className= {styles.galleryBackground}>
        <div className = {styles.searchBarContainer}>
          <textarea

            className = {styles.searchBar}
    
            placeholder="Search..."
            onChange={(e) => {changeNewValue(e.target.value)}}

          />
        </div>
  
          <div className = {styles.cardsContainer}>
          <p>{filter}</p>
            {filteredHorses.map((horse) => (
              <div className={styles.card}  key = {horse.name}>
                <div className = {styles.cardNameContainer}>
                  <p className = {styles.cardName}> {horse.name} </p>
                </div>
                <button className={styles.cardButton}>
                  <p className={styles.cardButtonText}>Adopt</p>
                </button>
                <img className={styles.cardImage} src = {horse.photo}></img>
            </div>
            ))}
        </div> 
        </div>
      </>
    )
  }

}

export default Home