import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainPageBackground}>
        <div className={styles.mainPageRight}>
          <div className={styles.mainPageRightText}>
          <h3 className={styles.mainPageSubtitle} >Adopt while you can!</h3>
          <h1 className={styles.mainPageTitle}>Care & Love</h1>
          <Link href = '/about'> 
            <button className={styles.mainPageButton}> Adopt </button>
          </Link>
          </div>
        </div>
      </div>
    </>
  )
}
